<%@ page language="java" contentType="text/html; charset=UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ page errorPage="error.html" %>

<jsp:useBean id="tree" class="ch.cdar.bll.reporting.ProjectTreeBean" scope="request" />
<% tree.setTreeId(Integer.parseInt(request.getParameter("treeid"))); %>
<% tree.checkCredentials(Integer.parseInt(request.getParameter("uid")), request.getParameter("accesstoken")); %>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=US-ASCII">
	<title>Consumer Tree Export: <%=tree.getTreeTitle()%></title>
	<link href="../vendor/css/bootstrap.css" rel="stylesheet">
	<link rel="icon" href="../app/img/favicon.ico" type="image/x-icon">
</head>

<body>
	<div class="container">

		<div class="page-header">
			<h1>Consumer Tree Report: <%=tree.getTreeTitle()%></h1>
			<p class="lead">Generated on: <%= tree.getCreationTime().toGMTString() %></p>
			<p class="lead">Generated by: <%= tree.getUsername() %></p>
		</div>

		<h2>Properties</h2>
		<div class="row">
			<div class="col-md-2">
				<strong>Node Description:</strong><br />
				<strong>Subnode Description:</strong>
			</div>
			<div class="col-md-10">
				 <%= tree.getCdarDescriptions().getNodeDescription() %><br />
				 <%= tree.getCdarDescriptions().getSubnodeDescription() %>
			</div>
		</div>
		<hr>
		
		<c:forEach items="${tree.getNodes()}" var="node">
			<a name="${node.getWikititle()}"></a>
			<h2><%= tree.getCdarDescriptions().getNodeDescription() %>: ${node.getTitle()}</h2>
			<a href="<%=tree.getCdarDescriptions().getWikiUrl()%>${node.getWikititle()}" target="_blank"><%=tree.getCdarDescriptions().getWikiUrl()%>${node.getWikititle()}</a>
			<table class="table table-bordered table-striped table-condensed table-hover" style="margin-top: 20px">
				<thead>
					<tr>
						<th class="col-md-2">Description</th>
						<th class="col-md-10">Content</th>
					</tr>
				</thead>
					<tr>
						<td><strong>Directory</strong></td>
						<td>
							${ tree.getDirectoryBreadcrumb(tree.getTreeTitle(), node.getDirectoryId()) }
						</td>
					</tr>
					<tr>
						<td><strong>Predecessor</strong></td>
						<td>
							<ul>
								<c:forEach items="${tree.getNodeLinks(true, node.getId())}" var="nodeLink">
									<li><a href="#${tree.getNode(nodeLink.getSourceId()).getWikititle()}">${tree.getNode(nodeLink.getSourceId()).getTitle()}</a> <c:if test="${nodeLink.getSubnodeId()!=0}">(from ${tree.getCdarDescriptions().getSubnodeDescription()}: <a href="#${tree.getSubnode(nodeLink.getSubnodeId()).getWikititle()}">${tree.getSubnode(nodeLink.getSubnodeId()).getTitle()}</a>)</c:if></li>
								</c:forEach>
								<c:if test="${tree.getNodeLinks(true, node.getId()).size()==0}">
									<li>No Predecessor</li>
								</c:if>
							</ul>
						</td>
					</tr>
					<tr>
						<td><strong>Successor</strong></td>
						<td>
							<ul>
								<c:forEach items="${tree.getNodeLinks(false, node.getId())}" var="nodeLink">
									<li><a href="#${tree.getNode(nodeLink.getTargetId()).getWikititle()}">${tree.getNode(nodeLink.getTargetId()).getTitle()}</a> <c:if test="${nodeLink.getSubnodeId()!=0}">(by ${tree.getCdarDescriptions().getSubnodeDescription()}: <a href="#${tree.getSubnode(nodeLink.getSubnodeId()).getWikititle()}">${tree.getSubnode(nodeLink.getSubnodeId()).getTitle()}</a>)</c:if>
								</c:forEach>
								<c:if test="${tree.getNodeLinks(false, node.getId()).size()==0}">
									<li>No Successor</li>
								</c:if>
							</ul>
						</td>
					</tr>
					<tr>
						<td><strong>Wiki Page</strong>
						<td>
							${ tree.getNodeWikiEntryHtml(node.getId()) }
						</td>
					</tr>
					<tr>
						<td><strong><%= tree.getCdarDescriptions().getNodeDescription() %> Status:</strong></td>
						<td>
							${ tree.getNodeStatus(node.getStatus()) }
						</td>
					</tr>
					<c:if test="${tree.getComments(node.getId()).size()!=0}">
						<tr>
							<td><strong>Comments:</strong></td>
							<td>
								<table class="table table-bordered table-striped table-condensed table-hover">
									<thead>
										<tr>
											<th class="col-md-2">Username</th>
											<th class="col-md-3">Date</th>
											<th class="col-md-7">Comment</th>
										</tr>
									</thead>
									<tbody>
										<c:forEach items="${tree.getComments(node.getId())}" var="comment">
											<tr>
												<td>${comment.getUsername()}</td>
												<td>${comment.getCreationTime()}</td>
												<td>${comment.getComment()}</td>
											</tr>
										</c:forEach>
									</tbody>
								</table>
							</td>
						</tr>
					</c:if>
				<tbody>
				
				</tbody>
			</table>
			
			
			<c:if test="${tree.getSubnodes(node.getId()).size()!=0}">
				<h3>${tree.getCdarDescriptions().getSubnodeDescription()}s:</h3>
				
				
				<table class="table table-bordered table-striped table-condensed table-hover">
					<thead>
						<tr>
							<th class="col-md-5">Title/Link</th>
							<th class="col-md-7">Content</th>
						</tr>
					</thead>
					<tbody>
					<c:forEach items="${tree.getSubnodes(node.getId())}" var="subnode">
						<tr>
						<td>
							<a name="${subnode.getWikititle()}"></a>
							<strong>${subnode.getTitle()}</strong><br />
							<a href="<%=tree.getCdarDescriptions().getWikiUrl()%>${subnode.getWikititle()}" target="_blank"><%=tree.getCdarDescriptions().getWikiUrl()%>${subnode.getWikititle()}</a>
						</td>
						<td>
							${tree.getSubnodeWikiEntryHtml(subnode.getId()) }
						</td>
					</c:forEach>
				</tbody>
				</table>
			</c:if>
			<hr>
		</c:forEach>
	</div>
</body>

</html>